libxsd is a runtime library for language mappings generated by
CodeSynthesis XSD, a W3C XML Schema to C++ data binding compiler.

See the LICENSE file for distribution conditions.

See the INSTALL file for prerequisites and installation instructions.

The project page is at http://www.codesynthesis.com/projects/xsd/

Send bug reports or any other feedback to the xsd-users@codesynthesis.com
mailing list.

